### ISSUE TITLE
Trying to setup on Windows 11 Visual Studio 

### ISSUE THREAD

**Issue by Brandon689** [micro-gl/nitro-gl#24]
I managed to fix some things for Windows but now I dont know what this error is about

nitro{gl} Exampler init
 - OpenGL {GL_VERSION} String:: 3.2.14800 Core Profile Context 22.3.1 30.0.15002.1004
 - OpenGL {GL_MAJOR_VERSION}.{GL_MINOR_VERSION}:: 3.2
 - OpenGL {GL_SHADING_LANGUAGE_VERSION}:: 4.60
INVALID_VALUE | code 1281 | file C:\Code2\August4\nitro\nitrogl\ogl\gl_texture.h ( line 200)
INVALID_ENUM | code 1280 | file C:\Code2\August4\nitro\nitrogl\ogl\gl_texture.h ( line 201)
Fragment shader failed to compile with the following errors:
ERROR: 73:7: error(#168) Reserved built-in name: __internal_porter_duff
ERROR: 78:3: error(#168) Reserved built-in name: __internal_porter_duff
ERROR: 81:33: error(#168) Reserved built-in name: __BLEND
ERROR: 81:34: error(#168) Reserved built-in name: __blend_in_place
ERROR: 81:36: error(#168) Reserved built-in name: __COMPOSITE
ERROR: error(#273) 5 compilation errors.  No code generated

**Comment by HendrixString** [comment]
Hi @Brandon689 ,
Can you share what file you try to compile ?
Which example file or your own original file ?
Plus, which compiler ?
Also, make sure it is not on OpenGL ES mode unless you have support for this

**Comment by HendrixString** [comment]
I think I found it here
https://github.com/micro-gl/nitro-gl/blob/d0e454fa071b00e88e10befad1801ade0e1f08b4/include/nitrogl/_internal/ogl_info.h

I need to rename major to minor versions in the condition macros for non ES open gl.

Can you try to do it?

**Comment by HendrixString** [comment]
@Brandon689 
I tried again and fixed some minor issues.
It works for me with cLion IDE on macOS.

Watch the following file
https://github.com/micro-gl/nitro-gl/blob/main/include/nitrogl/_internal/ogl_info.h

Can you report which Major / Minor version the macros dictate ?
If they are not aligned with your versions, please define them before
any includes in your program

**Comment by HendrixString** [comment]
@Brandon689 We are working on Windows support, I will update you once everything fits

**Comment by HendrixString** [comment]
Windows builds are now passing in CI,
I am closing the issue
